// Static seed for the cross-site UI-label cache (extension/content.js page translation).
// Maps the most ubiquitous English UI labels to their de-facto standard rendering per target language,
// so common chrome (nav/buttons) paints INSTANTLY on first load — zero model round-trip. These are only
// a bootstrap: the label cache keeps learning the model's own renderings across sites at runtime, and any
// page text not in this set falls through to the model normally. Source is English (the dominant UI
// language on the web); non-English source pages simply don't hit the seed and rely on the model + cache.
//
// Only well-established, unambiguous labels are included — a wrong seed is worse than a model call, so the
// list stays conservative. Targets without a seed below still get the runtime cross-site cache.
globalThis.LCC_PAGE_SEED = Object.freeze({
  Korean: {
    "Home": "홈", "Search": "검색", "Settings": "설정", "Log in": "로그인", "Login": "로그인",
    "Log out": "로그아웃", "Sign in": "로그인", "Sign up": "회원가입", "Share": "공유", "Reply": "답글",
    "Comment": "댓글", "Comments": "댓글", "Like": "좋아요", "Save": "저장", "Saved": "저장됨",
    "Edit": "편집", "Delete": "삭제", "Cancel": "취소", "Send": "보내기", "Submit": "제출",
    "Follow": "팔로우", "Following": "팔로잉", "Followers": "팔로워", "Subscribe": "구독", "Subscribed": "구독 중",
    "Notifications": "알림", "Messages": "메시지", "Profile": "프로필", "Account": "계정", "Menu": "메뉴",
    "More": "더보기", "Show more": "더 보기", "Show less": "간략히", "Read more": "자세히 보기", "View all": "전체 보기",
    "Loading…": "불러오는 중…", "Loading...": "불러오는 중...", "Next": "다음", "Previous": "이전", "Back": "뒤로",
    "Close": "닫기", "Open": "열기", "Download": "다운로드", "Upload": "업로드", "Copy": "복사",
    "Copied": "복사됨", "Done": "완료", "Continue": "계속", "Skip": "건너뛰기", "Help": "도움말",
    "Report": "신고", "Block": "차단", "Mute": "음소거", "Add": "추가", "Remove": "제거",
    "Create": "만들기", "New": "새로 만들기", "Filter": "필터", "Sort": "정렬", "Refresh": "새로고침",
    "Today": "오늘", "Yesterday": "어제", "Online": "온라인", "Offline": "오프라인", "Verified": "인증됨",
    "Learn more": "자세히 알아보기", "See all": "모두 보기", "Get started": "시작하기", "Sign out": "로그아웃",
    "Language": "언어", "Search…": "검색…",
  },
  Japanese: {
    "Home": "ホーム", "Search": "検索", "Settings": "設定", "Log in": "ログイン", "Login": "ログイン",
    "Log out": "ログアウト", "Sign in": "ログイン", "Sign up": "新規登録", "Share": "シェア", "Reply": "返信",
    "Comment": "コメント", "Comments": "コメント", "Like": "いいね", "Save": "保存", "Edit": "編集",
    "Delete": "削除", "Cancel": "キャンセル", "Send": "送信", "Submit": "送信", "Follow": "フォロー",
    "Following": "フォロー中", "Followers": "フォロワー", "Subscribe": "登録", "Notifications": "通知", "Messages": "メッセージ",
    "Profile": "プロフィール", "Account": "アカウント", "Menu": "メニュー", "More": "もっと見る", "Show more": "もっと見る",
    "Read more": "続きを読む", "Loading…": "読み込み中…", "Next": "次へ", "Previous": "前へ", "Back": "戻る",
    "Close": "閉じる", "Download": "ダウンロード", "Copy": "コピー", "Done": "完了", "Continue": "続ける",
    "Help": "ヘルプ", "Report": "報告", "Add": "追加", "Remove": "削除", "New": "新規",
    "Refresh": "更新", "Today": "今日", "Yesterday": "昨日", "Learn more": "詳しく見る", "See all": "すべて見る",
  },
  Chinese: {
    "Home": "首页", "Search": "搜索", "Settings": "设置", "Log in": "登录", "Login": "登录",
    "Log out": "退出登录", "Sign in": "登录", "Sign up": "注册", "Share": "分享", "Reply": "回复",
    "Comment": "评论", "Comments": "评论", "Like": "赞", "Save": "保存", "Edit": "编辑",
    "Delete": "删除", "Cancel": "取消", "Send": "发送", "Submit": "提交", "Follow": "关注",
    "Following": "正在关注", "Followers": "粉丝", "Subscribe": "订阅", "Notifications": "通知", "Messages": "消息",
    "Profile": "个人资料", "Account": "账户", "Menu": "菜单", "More": "更多", "Show more": "显示更多",
    "Read more": "阅读更多", "Loading…": "加载中…", "Next": "下一个", "Previous": "上一个", "Back": "返回",
    "Close": "关闭", "Download": "下载", "Copy": "复制", "Done": "完成", "Continue": "继续",
    "Help": "帮助", "Report": "举报", "Add": "添加", "Remove": "移除", "New": "新建",
    "Refresh": "刷新", "Today": "今天", "Yesterday": "昨天", "Learn more": "了解更多", "See all": "查看全部",
  },
  Spanish: {
    "Home": "Inicio", "Search": "Buscar", "Settings": "Configuración", "Log in": "Iniciar sesión", "Login": "Iniciar sesión",
    "Log out": "Cerrar sesión", "Sign in": "Iniciar sesión", "Sign up": "Registrarse", "Share": "Compartir", "Reply": "Responder",
    "Comment": "Comentar", "Comments": "Comentarios", "Like": "Me gusta", "Save": "Guardar", "Edit": "Editar",
    "Delete": "Eliminar", "Cancel": "Cancelar", "Send": "Enviar", "Submit": "Enviar", "Follow": "Seguir",
    "Following": "Siguiendo", "Followers": "Seguidores", "Subscribe": "Suscribirse", "Notifications": "Notificaciones", "Messages": "Mensajes",
    "Profile": "Perfil", "Account": "Cuenta", "Menu": "Menú", "More": "Más", "Show more": "Mostrar más",
    "Read more": "Leer más", "Loading…": "Cargando…", "Next": "Siguiente", "Previous": "Anterior", "Back": "Atrás",
    "Close": "Cerrar", "Download": "Descargar", "Copy": "Copiar", "Done": "Listo", "Continue": "Continuar",
    "Help": "Ayuda", "Report": "Reportar", "Add": "Añadir", "Remove": "Quitar", "New": "Nuevo",
    "Refresh": "Actualizar", "Today": "Hoy", "Yesterday": "Ayer", "Learn more": "Más información", "See all": "Ver todo",
  },
  French: {
    "Home": "Accueil", "Search": "Rechercher", "Settings": "Paramètres", "Log in": "Se connecter", "Login": "Se connecter",
    "Log out": "Se déconnecter", "Sign in": "Se connecter", "Sign up": "S'inscrire", "Share": "Partager", "Reply": "Répondre",
    "Comment": "Commenter", "Comments": "Commentaires", "Like": "J'aime", "Save": "Enregistrer", "Edit": "Modifier",
    "Delete": "Supprimer", "Cancel": "Annuler", "Send": "Envoyer", "Submit": "Envoyer", "Follow": "Suivre",
    "Following": "Abonnements", "Followers": "Abonnés", "Subscribe": "S'abonner", "Notifications": "Notifications", "Messages": "Messages",
    "Profile": "Profil", "Account": "Compte", "Menu": "Menu", "More": "Plus", "Show more": "Afficher plus",
    "Read more": "Lire la suite", "Loading…": "Chargement…", "Next": "Suivant", "Previous": "Précédent", "Back": "Retour",
    "Close": "Fermer", "Download": "Télécharger", "Copy": "Copier", "Done": "Terminé", "Continue": "Continuer",
    "Help": "Aide", "Report": "Signaler", "Add": "Ajouter", "Remove": "Retirer", "New": "Nouveau",
    "Refresh": "Actualiser", "Today": "Aujourd'hui", "Yesterday": "Hier", "Learn more": "En savoir plus", "See all": "Tout voir",
  },
  German: {
    "Home": "Startseite", "Search": "Suchen", "Settings": "Einstellungen", "Log in": "Anmelden", "Login": "Anmelden",
    "Log out": "Abmelden", "Sign in": "Anmelden", "Sign up": "Registrieren", "Share": "Teilen", "Reply": "Antworten",
    "Comment": "Kommentieren", "Comments": "Kommentare", "Like": "Gefällt mir", "Save": "Speichern", "Edit": "Bearbeiten",
    "Delete": "Löschen", "Cancel": "Abbrechen", "Send": "Senden", "Submit": "Senden", "Follow": "Folgen",
    "Following": "Gefolgt", "Followers": "Follower", "Subscribe": "Abonnieren", "Notifications": "Benachrichtigungen", "Messages": "Nachrichten",
    "Profile": "Profil", "Account": "Konto", "Menu": "Menü", "More": "Mehr", "Show more": "Mehr anzeigen",
    "Read more": "Weiterlesen", "Loading…": "Wird geladen…", "Next": "Weiter", "Previous": "Zurück", "Back": "Zurück",
    "Close": "Schließen", "Download": "Herunterladen", "Copy": "Kopieren", "Done": "Fertig", "Continue": "Weiter",
    "Help": "Hilfe", "Report": "Melden", "Add": "Hinzufügen", "Remove": "Entfernen", "New": "Neu",
    "Refresh": "Aktualisieren", "Today": "Heute", "Yesterday": "Gestern", "Learn more": "Mehr erfahren", "See all": "Alle ansehen",
  },
  Russian: {
    "Home": "Главная", "Search": "Поиск", "Settings": "Настройки", "Log in": "Войти", "Login": "Войти",
    "Log out": "Выйти", "Sign in": "Войти", "Sign up": "Регистрация", "Share": "Поделиться", "Reply": "Ответить",
    "Comment": "Комментировать", "Comments": "Комментарии", "Like": "Нравится", "Save": "Сохранить", "Edit": "Изменить",
    "Delete": "Удалить", "Cancel": "Отмена", "Send": "Отправить", "Submit": "Отправить", "Follow": "Подписаться",
    "Following": "Подписки", "Followers": "Подписчики", "Subscribe": "Подписаться", "Notifications": "Уведомления", "Messages": "Сообщения",
    "Profile": "Профиль", "Account": "Аккаунт", "Menu": "Меню", "More": "Ещё", "Show more": "Показать ещё",
    "Read more": "Читать далее", "Loading…": "Загрузка…", "Next": "Далее", "Previous": "Назад", "Back": "Назад",
    "Close": "Закрыть", "Download": "Скачать", "Copy": "Копировать", "Done": "Готово", "Continue": "Продолжить",
    "Help": "Помощь", "Report": "Пожаловаться", "Add": "Добавить", "Remove": "Удалить", "New": "Создать",
    "Refresh": "Обновить", "Today": "Сегодня", "Yesterday": "Вчера", "Learn more": "Подробнее", "See all": "Показать все",
  },
  Portuguese: {
    "Home": "Início", "Search": "Pesquisar", "Settings": "Configurações", "Log in": "Entrar", "Login": "Entrar",
    "Log out": "Sair", "Sign in": "Entrar", "Sign up": "Cadastrar-se", "Share": "Compartilhar", "Reply": "Responder",
    "Comment": "Comentar", "Comments": "Comentários", "Like": "Curtir", "Save": "Salvar", "Edit": "Editar",
    "Delete": "Excluir", "Cancel": "Cancelar", "Send": "Enviar", "Submit": "Enviar", "Follow": "Seguir",
    "Following": "Seguindo", "Followers": "Seguidores", "Subscribe": "Inscrever-se", "Notifications": "Notificações", "Messages": "Mensagens",
    "Profile": "Perfil", "Account": "Conta", "Menu": "Menu", "More": "Mais", "Show more": "Mostrar mais",
    "Read more": "Leia mais", "Loading…": "Carregando…", "Next": "Próximo", "Previous": "Anterior", "Back": "Voltar",
    "Close": "Fechar", "Download": "Baixar", "Copy": "Copiar", "Done": "Concluído", "Continue": "Continuar",
    "Help": "Ajuda", "Report": "Denunciar", "Add": "Adicionar", "Remove": "Remover", "New": "Novo",
    "Refresh": "Atualizar", "Today": "Hoje", "Yesterday": "Ontem", "Learn more": "Saiba mais", "See all": "Ver tudo",
  },
});
